---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13
  environment:
    username:
      from_secret: username
    token:
      from_secret: token
  commands:
  - go env -w GOPRIVATE=github.com/appleboy
  - git --help
  - go build .

